package co.fr8.terminal.base;

/**
 * TODO: DOCUMENT
 */
public enum ActivityErrorCode {
  SQL_SERVER_CONNECTION_STRING_MISSING,
  SQL_SERVER_CONNECTION_FAILED,
  PAYLOAD_DATA_MISSING,
  PAYLOAD_DATA_INVALID,
  AUTH_TOKEN_NOT_PROVIDED_OR_INVALID,
  DESIGN_TIME_DATA_MISSING;
}
